### ISSUE TITLE
Add prefix cache implementation

### ISSUE THREAD

**Issue by IkBenOlie5** [FasterSpeeding/Sake#30]
It would be basically the same as GuildCache etc but for prefixes. The way the user interacts with it should be discussed tho (if it'd be inside RedisCache by default or not).

im willing to do it btw

**Comment by IkBenOlie5** [comment]
Is it a good idea or not?

**Comment by FasterSpeeding** [comment]
It's a good idea and for how this'd work interface wise I'm thinking that with the recent addition of https://github.com/FasterSpeeding/Sake/commit/fb2219d139ae36ac977e5558d3304889ab284e20 redis.ResourceClient could have a toggle on it which switches it between two different key strategies where one formats all the keys as something along the lines of `"{index}:{actual_id}"` (where overrides don't effect the used index) while the other is just the actual id and a short hand method which sets overrides for all the known indexes so that switching over to a prefix cache implementation would look something like
```py
cli = RedisClient(...).key_prefixing(True).override_all_indexes(int)
 ```

**Comment by IkBenOlie5** [comment]
Currently have https://github.com/IkBenOlie5/Sake/tree/prefix-cache
and the way you would interact with it would be

```py
from sake import redis

class MyCache(redis.RedisCache, redis.PrefixCache):
    pass
```

btw: rn you have to manually set prefixes and I'm trying to make it automatically but that would mean that I need to get the prefix from an hikari.Message object.

**Comment by FasterSpeeding** [comment]
Ok so I totally mis-interpreted what you meant by "prefix cache" but that other idea i was thinking about should probably also be implemented so i'ma move that to another issue

**Comment by FasterSpeeding** [comment]
You can open a PR for this if you want and yeah I agree that this probably shouldn't be included in the standard RedisCache, seems like by nature this one will probably have to be a manual cache store instead of listening to events itself which is fine with me

**Comment by FasterSpeeding** [comment]
> Currently have https://github.com/IkBenOlie5/Sake/tree/prefix-cache
> and the way you would interact with it would be
> 
> ```python
> from sake import redis
> 
> class MyCache(redis.RedisCache, redis.PrefixCache):
>     pass
> ```
> 
> btw: rn you have to manually set prefixes and I'm trying to make it automatically but that would mean that I need to get the prefix from an hikari.Message object.

This all looks pretty good right now, just got a couple of things i'll probably comment on once you open a PR for this. 
(and you can PR this into master, I'll rebase task/raw-dispatch once it's merged)

**Comment by IkBenOlie5** [comment]
> You can open a PR for this if you want and yeah I agree that this probably shouldn't be included in the standard RedisCache, seems like by nature this one will probably have to be a manual cache store instead of listening to events itself which is fine with me

yeah, its impossible to get the prefix without knowing what the commands are etc
