### ISSUE TITLE
Cant' install from pip 'cause the library "hikari-yoyo" can't be found.

### ISSUE THREAD

**Issue by FlinnkDark** [FasterSpeeding/Sake#61]
I can't install hikari sake 'cause can't found "hikari-yoyo", I search the repo and yoyo was been renamed to yuyo, but when try to install : "pip install hikari-sake", i saw this: ERROR: No matching distribution found for hikari-yoyo~=0.0.2 (from hikari-sake)

Trying install by the repo:
Running command git clone -q https://github.com/FasterSpeeding/sake /tmp/pip-req-build-v5ipyq1u
  WARNING: Did not find branch or tag 'task/dispatch', assuming revision or ref.
  Running command git checkout -q task/dispatch
  error: pathspec 'task/dispatch' did not match any file(s) known to git

**Comment by FasterSpeeding** [comment]
looks like you found the solution but for anybody else who has an issue like this, pip is ignoring the alpha v1 releases, you should be using those not v0. To hopefully solve this i'm going to yank v0.0.1 (which should make pip fallback to the alpha releases)

**Comment by FlinnkDark** [comment]
Was typing my comment when you replied jaja, the temporary solution that I found was install by the repo (the last time I tried, the url that I used was https://github.com/FasterSpeeding/sake@task/dispatch)
**Correct url:**
pip install git+https://github.com/FasterSpeeding/sake
